version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_CONFIG}:/app/data/configs
      - ${HOMARR_ICONS}:/app/public/icons
      - ${HOMARR_DATA}:/data
    ports:
      - '7575:7575'
    networks:
      - homelab_network
