---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${DATA}/komga:/config
      - ${BOOKS}:/data
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped