version: "3.3"

services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
        - 3038:8080
    environment:
      - DOCKER_ENABLE_SECURITY=false
    volumes:
      - ${DATA}/StirlingPDF/trainingData:/usr/share/tessdata
      - ${DATA}/StirlingPDF/extraConfigs:/configs
      - ${DATA}/StirlingPDF/customFiles:/customFiles/
      - ${DATA}/StirlingPDF/logs:/logs/
      - ${DATA}/StirlingPDF/pipeline:/pipeline/
    networks:
      - homelab_network