version: "3.8"
name: homelab

include:
  - apps/kiss.yml # 8080
  - apps/komga.yml # 25600
  - apps/n8n.yml # 5678
  - apps/jellyfin.yml # 8096 7359
  - apps/seerr.yml # 5055
  - apps/radarr.yml # 7878
  - apps/sonarr.yml # 8989
  - apps/prowlarr.yml # 9696
  - apps/bazarr.yml # 6767
  - apps/profilarr.yml # 6868
  - apps/flaresolverr.yml # 8191
  - apps/deluge.yml # 8112 6881 58846
  - apps/ezbookkeeping.yml # 7986

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    env_file: ".env"
    command: tunnel --no-autoupdate run --token "$CLOUDFLARED_TOKEN"
    networks:
      - homelab_network

networks:
  homelab_network:
    driver: bridge
