version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    stdin_open: true
    tty: true
    env_file: ".env"
    ports:
        - 5678:5678
    volumes:
      - ${DATA}/n8n:/home/node/.n8n
    networks:
      - homelab_network