version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
        - 3001:3001
    volumes:
      - ${DATA}/uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab_network