version: "3.8"

services:
  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    restart: unless-stopped
    ports:
        - 11470:11470
        - 12470:12470
    networks:
      - homelab_network