version: "3.8"

services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    restart: unless-stopped
    tty: true
    command: serve -p 9000
    ports:
      - 9000:9000
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab_network